# Generated by Django 6.0.5 on 2026-06-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_company_name_company_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='India', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expreience',
            field=models.CharField(default='Fresher', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(default='Graduate', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='Full Time', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='General', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='Day', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
