# Generated by Django 6.0.5 on 2026-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_candidate_country_candidate_expreience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expreience',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='jobdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='shift',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
