# Generated by Django 6.0.5 on 2026-06-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_candidate_profile_pic_alter_candidate_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='app/img/candidate'),
        ),
    ]
