# Generated by Django 6.0.5 on 2026-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_candidate_country_alter_candidate_expreience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='jobdescription',
            new_name='job_description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='expreience',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='highestedu',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='jobcategory',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='shift',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_catagry',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='max_salary',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.URLField(default='', max_length=150),
        ),
    ]
