# Generated by Django 6.0.5 on 2026-06-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_jobdescription_candidate_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
