# Generated by Django 6.0.5 on 2026-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_web',
            field=models.CharField(default='', max_length=250),
        ),
    ]
