# Generated by Django 6.0.5 on 2026-06-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='companyimage',
            field=models.ImageField(default='', upload_to='app/img/company'),
        ),
    ]
