# Generated by Django 6.0.5 on 2026-06-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_jobdetails_companyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyaddress',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companycontact',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyemail',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyimage',
            field=models.ImageField(default='', upload_to='app/img/jobpost'),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companyname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='companywebsite',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='jobname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='qualification',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='resposibilities',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='salarypackeg',
            field=models.CharField(default='', max_length=250),
        ),
    ]
