# Generated by Django 6.0.5 on 2026-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_jobdetails_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='companyimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='app/img/jobpost'),
        ),
    ]
