# Generated by Django 6.0.5 on 2026-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_jobdetails_companyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='expreience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
