# Generated by Django 6.0.5 on 2026-06-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_jobdetails_expreience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('min_salary', models.CharField(default='', max_length=200)),
                ('max_salary', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
                ('resume', models.FileField(upload_to='app/resume/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
