# Generated by Django 6.0.5 on 2026-06-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='applylist',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applylist',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='applylist',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applylist',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='applylist',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='applylist',
            name='firstname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applylist',
            name='jobname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='applylist',
            name='lastname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='applylist',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
